title: Aravind R K # your name (or website title) here
logo: "/imageedit_1_5470984225.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Data Engineer
  <br><br>
  <a href="mailto:rkaravind1992@gmail.com">rkaravind1992@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/aravind-r-k-739605122/">LinkedIn profile</a>
  <br>
  <a href="https://github.com/boun7yhunt3r/">Gihub</a> 
  <br>
  <a href="https://medium.com/@aravindrk">Medium</a> 
theme: jekyll-theme-minimal
